# -*- coding: utf-8 -*-
"""AI-Lab-week2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nn0q-Z6a7GpNb5tPye_bn-yB1JvYplXF
"""

#Age Criteria Program
n = int(input("Enter your age "))
if(n<18):
  print("You are a kid")
elif(n>=18 and n<65):
  print("You are a adult")
elif(n>=65):
  print("You are senior citizen")

#Multiplication of numbers
n =int(input("Enter the number "))
for i in range(1,11):
  print(n ,'*', i, ' =' , i*n)

#pattern1
n = int(input("Enter the number "))
for i in range(1,n+1):
  for j in range(1,i+1):
    print(i, end=" ")
  print("")

#pattern2
n = int(input("Enter the number "))
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j, end=" ")
  print("") #or print('\r')

#BubbleSort
def bubbleSort(arr,n):
  for i in range(n):
    for j in range(0,n-i-1):
      if(arr[j] > arr[j+1]):
        arr[j],arr[j+1] = arr[j+1],arr[j]
n = int(input("Enter the size of array "))
arr=[]
print("Enter the array elements ")
for i in range(n):
  arr.append(int(input())) #enter each number line wise
bubbleSort(arr,n)
print("Sorted Array:")
#for i in range(n):
#  print(arr[i], end=" ")
print(arr)

#Reverse Number
n = int(input("Enter the number "))
sum = 0
while(n>0):
  sum = (sum*10) + (n%10)
  n = n//10
print("Reversed Number is :",sum)